Improve Events API
FairRootGroup/FairMQ pull request #352
Opened 2021-05-04 07:59 UTC by ktf

If the call is interrupted by a signal, this will throw, which we clearly do not want. Simplifying the API to let the user decide what to do on error is probably the best option.

See also https://alice.its.cern.ch/jira/browse/O2-2257.

---

2021-05-04 08:36 UTC, dennisklein requested changes
Mismatching brackets:
```
zeromq/Socket.h:329:76: error: expected ';' after return statement [clang-diagnostic-error]
        return zmq_getsockopt(fSocket, ZMQ_EVENTS, events, &eventsSize) < 0);
```

Also squash all those three commits into one pls.

2021-05-04 19:38 UTC, ktf commented
I wish github had a "squash all commits" button...

2021-05-04 19:40 UTC, ktf commented
Done!

2021-05-04 20:46 UTC, dennisklein commented
> I wish github had a "squash all commits" button...

It has, but it is disabled on this repo ;)

2021-05-04 20:49 UTC, dennisklein approved these changes

2021-05-04 20:54 UTC, dennisklein commented
This will be included in `v1.4.36` which we will release at the end of the week - I still have to move the alice hotfixes (`v1.4.35.{1,2}`) from last week properly into our `dev` branch to be also included. We will open the according bump PR to alidist then, too. Thx for the contribution!

2021-05-04 20:54 UTC, merged

2021-05-05 09:00 UTC, ktf commented
Thank you!